use std::error::Error;
use std::fmt;
use std::fs::{self, OpenOptions, Permissions};
use std::io::{self, IsTerminal, Write};
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::environment::ShellKind;
use crate::secret_store::{KeychainCoordinates, SecretStore};

const ZSH_START: &str = "# >>> ai-world >>>";
const ZSH_END: &str = "# <<< ai-world <<<";
const ZSH_BLOCK: &str = "# >>> ai-world >>>\nif command -v aiw >/dev/null 2>&1; then\n  eval \"$(aiw env zsh)\"\nfi\n# <<< ai-world <<<";
const FISH_FILE: &str =
    "# Generated by ai-world. Do not edit.\nif type -q aiw\n    aiw env fish | source\nend\n";
const BACKUP_SERVICE: &str = "ai-world.shell-backup";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IntegrationStatus {
    Missing,
    Current,
    Drifted,
    Malformed,
}

impl fmt::Display for IntegrationStatus {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Missing => formatter.write_str("missing"),
            Self::Current => formatter.write_str("current"),
            Self::Drifted => formatter.write_str("drifted"),
            Self::Malformed => formatter.write_str("malformed"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InstallOutcome {
    pub changed: bool,
    pub status: IntegrationStatus,
    pub backup: Option<KeychainCoordinates>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IntegrationError(String);

pub trait Confirmer {
    fn confirm(&self, prompt: &str) -> Result<bool, io::Error>;
}

#[derive(Default)]
pub struct StdinConfirmer;

impl Confirmer for StdinConfirmer {
    fn confirm(&self, prompt: &str) -> Result<bool, io::Error> {
        if io::stdout().is_terminal() {
            print!("\u{1b}[36m◆\u{1b}[0m {prompt} \u{1b}[2m[y/N]\u{1b}[0m ");
        } else {
            print!("{prompt} [y/N] ");
        }
        io::stdout().flush()?;
        let mut answer = String::new();
        io::stdin().read_line(&mut answer)?;
        Ok(matches!(
            answer.trim().to_ascii_lowercase().as_str(),
            "y" | "yes"
        ))
    }
}

pub struct ShellIntegrationManager<'a> {
    home: PathBuf,
    confirmer: &'a dyn Confirmer,
    store: &'a dyn SecretStore,
}

impl<'a> ShellIntegrationManager<'a> {
    pub fn new(
        home: impl Into<PathBuf>,
        confirmer: &'a dyn Confirmer,
        store: &'a dyn SecretStore,
    ) -> Self {
        Self {
            home: home.into(),
            confirmer,
            store,
        }
    }

    pub fn status(&self, shell: ShellKind) -> Result<IntegrationStatus, IntegrationError> {
        let target = self.target(shell);
        let snapshot = read_snapshot(&target)?;
        Ok(integration_status(shell, snapshot.content.as_deref()))
    }

    pub fn install(&self, shell: ShellKind) -> Result<InstallOutcome, IntegrationError> {
        let target = self.target(shell);
        let initial = read_snapshot(&target)?;
        let status = integration_status(shell, initial.content.as_deref());
        if status == IntegrationStatus::Current {
            return Ok(InstallOutcome {
                changed: false,
                status,
                backup: None,
            });
        }
        if status == IntegrationStatus::Malformed {
            return Err(IntegrationError(format!(
                "{} contains malformed ai-world markers",
                target.display()
            )));
        }
        if initial.is_symlink {
            return Err(IntegrationError(format!(
                "refusing to replace symbolic link '{}'",
                target.display()
            )));
        }
        let action = if status == IntegrationStatus::Missing {
            "Install"
        } else {
            "Replace drifted"
        };
        if !self
            .confirmer
            .confirm(&format!(
                "{action} {} integration in {}?",
                shell,
                target.display()
            ))
            .map_err(|error| IntegrationError(format!("cannot read confirmation: {error}")))?
        {
            return Ok(InstallOutcome {
                changed: false,
                status,
                backup: None,
            });
        }

        let current = read_snapshot(&target)?;
        if !same_snapshot(&current, &initial) {
            return Err(IntegrationError(format!(
                "'{}' changed while confirmation was pending; retry installation",
                target.display()
            )));
        }
        if current.is_symlink {
            return Err(IntegrationError(format!(
                "refusing to replace symbolic link '{}'",
                target.display()
            )));
        }

        let backup = initial
            .content
            .as_deref()
            .map(|content| self.back_up(shell, content))
            .transpose()?;
        let updated = match shell {
            ShellKind::Zsh => update_zsh(initial.content.as_deref().unwrap_or_default(), status)?,
            ShellKind::Fish => FISH_FILE.to_owned(),
        };
        write_atomic(&target, &updated, &initial)?;
        Ok(InstallOutcome {
            changed: true,
            status: IntegrationStatus::Current,
            backup,
        })
    }

    fn target(&self, shell: ShellKind) -> PathBuf {
        match shell {
            ShellKind::Zsh => self.home.join(".zshrc"),
            ShellKind::Fish => self.home.join(".config/fish/conf.d/ai-world.fish"),
        }
    }

    fn back_up(
        &self,
        shell: ShellKind,
        content: &str,
    ) -> Result<KeychainCoordinates, IntegrationError> {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_err(|error| IntegrationError(format!("system clock is invalid: {error}")))?
            .as_nanos();
        let coordinates = KeychainCoordinates::new(BACKUP_SERVICE, format!("{shell}-{timestamp}"));
        self.store
            .set(&coordinates, content.as_bytes())
            .map_err(|error| {
                IntegrationError(format!("cannot write shell backup to Keychain: {error}"))
            })?;
        Ok(coordinates)
    }
}

struct TargetSnapshot {
    content: Option<String>,
    permissions: Option<Permissions>,
    is_symlink: bool,
}

fn read_snapshot(path: &Path) -> Result<TargetSnapshot, IntegrationError> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => Some(metadata),
        Err(error) if error.kind() == io::ErrorKind::NotFound => None,
        Err(error) => {
            return Err(IntegrationError(format!(
                "cannot inspect '{}': {error}",
                path.display()
            )));
        }
    };
    let is_symlink = metadata
        .as_ref()
        .is_some_and(|metadata| metadata.file_type().is_symlink());
    let content = read_optional(path)?;
    Ok(TargetSnapshot {
        content,
        permissions: metadata.map(|metadata| metadata.permissions()),
        is_symlink,
    })
}

fn integration_status(shell: ShellKind, content: Option<&str>) -> IntegrationStatus {
    let Some(content) = content else {
        return IntegrationStatus::Missing;
    };
    match shell {
        ShellKind::Zsh => zsh_status(content),
        ShellKind::Fish if content == FISH_FILE => IntegrationStatus::Current,
        ShellKind::Fish => IntegrationStatus::Drifted,
    }
}

fn same_snapshot(left: &TargetSnapshot, right: &TargetSnapshot) -> bool {
    left.content == right.content
        && left.is_symlink == right.is_symlink
        && same_permissions(left.permissions.as_ref(), right.permissions.as_ref())
}

#[cfg(unix)]
fn same_permissions(left: Option<&Permissions>, right: Option<&Permissions>) -> bool {
    use std::os::unix::fs::PermissionsExt;
    left.map(PermissionsExt::mode) == right.map(PermissionsExt::mode)
}

#[cfg(not(unix))]
fn same_permissions(left: Option<&Permissions>, right: Option<&Permissions>) -> bool {
    left.map(Permissions::readonly) == right.map(Permissions::readonly)
}

fn read_optional(path: &Path) -> Result<Option<String>, IntegrationError> {
    match fs::read_to_string(path) {
        Ok(content) => Ok(Some(content)),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(IntegrationError(format!(
            "cannot read '{}': {error}",
            path.display()
        ))),
    }
}

fn zsh_status(content: &str) -> IntegrationStatus {
    let starts = content.match_indices(ZSH_START).collect::<Vec<_>>();
    let ends = content.match_indices(ZSH_END).collect::<Vec<_>>();
    if starts.is_empty() && ends.is_empty() {
        return IntegrationStatus::Missing;
    }
    if starts.len() != 1 || ends.len() != 1 || starts[0].0 >= ends[0].0 {
        return IntegrationStatus::Malformed;
    }
    let managed = &content[starts[0].0..ends[0].0 + ZSH_END.len()];
    if managed == ZSH_BLOCK {
        IntegrationStatus::Current
    } else {
        IntegrationStatus::Drifted
    }
}

fn update_zsh(content: &str, status: IntegrationStatus) -> Result<String, IntegrationError> {
    match status {
        IntegrationStatus::Missing => {
            let mut updated = content.to_owned();
            if !updated.is_empty() && !updated.ends_with('\n') {
                updated.push('\n');
            }
            if !updated.is_empty() {
                updated.push('\n');
            }
            updated.push_str(ZSH_BLOCK);
            updated.push('\n');
            Ok(updated)
        }
        IntegrationStatus::Drifted => {
            let start = content
                .find(ZSH_START)
                .expect("drifted block has start marker");
            let end = content.find(ZSH_END).expect("drifted block has end marker") + ZSH_END.len();
            Ok(format!(
                "{}{}{}",
                &content[..start],
                ZSH_BLOCK,
                &content[end..]
            ))
        }
        _ => Err(IntegrationError(
            "zsh integration cannot be updated from this state".into(),
        )),
    }
}

fn write_atomic(
    path: &Path,
    content: &str,
    expected: &TargetSnapshot,
) -> Result<(), IntegrationError> {
    let parent = path.parent().ok_or_else(|| {
        IntegrationError(format!(
            "integration path '{}' has no parent",
            path.display()
        ))
    })?;
    fs::create_dir_all(parent).map_err(|error| {
        IntegrationError(format!(
            "cannot create directory '{}': {error}",
            parent.display()
        ))
    })?;
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("integration");
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|error| IntegrationError(format!("system clock is invalid: {error}")))?
        .as_nanos();
    let temporary = parent.join(format!(
        ".{file_name}.ai-world.tmp.{}-{nonce}",
        std::process::id()
    ));
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut file = options.open(&temporary).map_err(|error| {
        IntegrationError(format!("cannot create '{}': {error}", temporary.display()))
    })?;
    let cleanup = TemporaryFile(temporary.clone());
    file.write_all(content.as_bytes()).map_err(|error| {
        IntegrationError(format!("cannot write '{}': {error}", temporary.display()))
    })?;
    file.sync_all().map_err(|error| {
        IntegrationError(format!("cannot sync '{}': {error}", temporary.display()))
    })?;
    match expected.permissions.clone() {
        Some(permissions) => fs::set_permissions(&temporary, permissions).map_err(|error| {
            IntegrationError(format!(
                "cannot set permissions on '{}': {error}",
                temporary.display()
            ))
        })?,
        None => secure_file(&temporary)?,
    }
    let latest = read_snapshot(path)?;
    if !same_snapshot(&latest, expected) {
        return Err(IntegrationError(format!(
            "'{}' changed before atomic replacement; retry installation",
            path.display()
        )));
    }
    fs::rename(&temporary, path).map_err(|error| {
        IntegrationError(format!("cannot replace '{}': {error}", path.display()))
    })?;
    drop(cleanup);
    Ok(())
}

struct TemporaryFile(PathBuf);

impl Drop for TemporaryFile {
    fn drop(&mut self) {
        let _ = fs::remove_file(&self.0);
    }
}

#[cfg(unix)]
fn secure_file(path: &Path) -> Result<(), IntegrationError> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(0o600)).map_err(|error| {
        IntegrationError(format!("cannot protect file '{}': {error}", path.display()))
    })
}

#[cfg(not(unix))]
fn secure_file(_path: &Path) -> Result<(), IntegrationError> {
    Ok(())
}

impl fmt::Display for IntegrationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for IntegrationError {}
